version: '2'
services:
    jini-app:
        image: jini
        external_links:
            - jini-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jini?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jini-mysql:
        extends:
            file: mysql.yml
            service: jini-mysql
